### ISSUE TITLE
O HermiT reasoner está acusando erro na hierarquia da ontologia

### ISSUE THREAD

**Issue by alcideslopes** [BDI-UFRGS/O3POntology#1]
O Protege esta devolvendo o seguinte erro ao inicializar o HermiT reasoner

ERROR  16:03:41  An error occurred during reasoning: The given property hierarchy is not regular..
java.lang.IllegalArgumentException: The given property hierarchy is not regular.
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.buildPropertyOrdering(ObjectPropertyInclusionManager.java:629) ~[na:na]
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.createAutomata(ObjectPropertyInclusionManager.java:195) ~[na:na]
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.<init>(ObjectPropertyInclusionManager.java:58) ~[na:na]
	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:156) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:211) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:202) ~[na:na]
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:176) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createHermiTOWLReasoner(ReasonerFactory.java:51) ~[na:na]
	at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:19) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

**Comment by n0santos** [comment]
resolvi aqui
